[2025-07-28T12:51:00.894-0300] {processor.py:161} INFO - Started process (PID=8054) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T12:51:00.900-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T12:51:00.912-0300] {logging_mixin.py:188} INFO - [2025-07-28T12:51:00.907-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T12:51:01.017-0300] {logging_mixin.py:188} INFO - [2025-07-28T12:51:00.998-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T12:51:01.024-0300] {logging_mixin.py:188} INFO - [2025-07-28T12:51:01.021-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T12:51:01.028-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T12:51:01.097-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.240 seconds
[2025-07-28T13:10:18.682-0300] {processor.py:161} INFO - Started process (PID=8676) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:10:18.701-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:10:18.711-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:10:18.706-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:10:18.803-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:10:18.786-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:10:18.811-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:10:18.807-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:10:18.814-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:10:18.873-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.231 seconds
[2025-07-28T13:46:44.280-0300] {processor.py:161} INFO - Started process (PID=8755) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:46:44.285-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:46:44.291-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:46:44.289-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:46:44.380-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:46:44.366-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:46:44.386-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:46:44.384-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:46:44.390-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:46:44.447-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.201 seconds
[2025-07-28T13:48:27.365-0300] {processor.py:161} INFO - Started process (PID=8808) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:48:27.371-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:48:27.380-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:48:27.376-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:48:27.457-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:48:27.441-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:48:27.463-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:48:27.460-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:48:27.466-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:48:27.529-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2025-07-28T13:51:27.081-0300] {processor.py:161} INFO - Started process (PID=8915) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:51:27.086-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:51:27.092-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:51:27.089-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:51:27.164-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:51:27.148-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:51:27.169-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:51:27.167-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:51:27.172-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:51:27.232-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.182 seconds
[2025-07-28T13:53:02.481-0300] {processor.py:161} INFO - Started process (PID=8977) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:53:02.486-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:53:02.496-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:53:02.492-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:53:02.590-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:53:02.572-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:53:02.597-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:53:02.594-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:53:02.601-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:53:02.675-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.232 seconds
[2025-07-28T13:56:10.381-0300] {processor.py:161} INFO - Started process (PID=9086) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:56:10.384-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:56:10.387-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:56:10.385-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:56:10.416-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:56:10.410-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:56:10.418-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:56:10.417-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:56:10.419-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:56:10.446-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-07-28T13:57:49.564-0300] {processor.py:161} INFO - Started process (PID=9174) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:57:49.567-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:57:49.570-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:57:49.568-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:57:49.600-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:57:49.593-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:57:49.602-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:57:49.601-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:57:49.603-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:57:49.628-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2025-07-28T13:59:59.769-0300] {processor.py:161} INFO - Started process (PID=9269) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:59:59.772-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T13:59:59.776-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:59:59.774-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:59:59.808-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:59:59.801-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T13:59:59.811-0300] {logging_mixin.py:188} INFO - [2025-07-28T13:59:59.810-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T13:59:59.813-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T13:59:59.838-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-07-28T14:01:35.222-0300] {processor.py:161} INFO - Started process (PID=9349) to work on /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T14:01:35.225-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-28T14:01:35.228-0300] {logging_mixin.py:188} INFO - [2025-07-28T14:01:35.226-0300] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T14:01:35.259-0300] {logging_mixin.py:188} INFO - [2025-07-28T14:01:35.253-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-28T14:01:35.262-0300] {logging_mixin.py:188} INFO - [2025-07-28T14:01:35.261-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-28T14:01:35.263-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-28T14:01:35.287-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Usuario/Downloads/Automações/Climate-AgriTech-MLOps/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
